// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Unit", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pounds",
                            Symbol = "lb"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kilograms",
                            Symbol = "kg"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Stone",
                            Symbol = "st"
                        });
                });

            modelBuilder.Entity("Domain.WeightLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("WeightLog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5bf4ce4c-13b1-469e-9e6a-c082410a88c2"),
                            Date = new DateTime(2023, 3, 10, 15, 44, 35, 805, DateTimeKind.Utc).AddTicks(1589),
                            Unit = 1,
                            Weight = 220m
                        },
                        new
                        {
                            Id = new Guid("317beecf-3fce-4f7d-9639-6d83a017a6b5"),
                            Date = new DateTime(2023, 4, 10, 15, 44, 35, 805, DateTimeKind.Utc).AddTicks(1599),
                            Unit = 1,
                            Weight = 216m
                        },
                        new
                        {
                            Id = new Guid("211627cf-ebf9-4a9e-9cab-a2c52c09c9c2"),
                            Date = new DateTime(2023, 5, 10, 15, 44, 35, 805, DateTimeKind.Utc).AddTicks(1602),
                            Unit = 1,
                            Weight = 212m
                        },
                        new
                        {
                            Id = new Guid("a1a030c7-c45e-4c74-8df2-ee22396f91c9"),
                            Date = new DateTime(2023, 6, 10, 15, 44, 35, 805, DateTimeKind.Utc).AddTicks(1603),
                            Unit = 1,
                            Weight = 208m
                        },
                        new
                        {
                            Id = new Guid("ea6963b2-09f1-4c29-9deb-d45cb04ceb48"),
                            Date = new DateTime(2023, 7, 10, 15, 44, 35, 805, DateTimeKind.Utc).AddTicks(1605),
                            Unit = 1,
                            Weight = 204m
                        },
                        new
                        {
                            Id = new Guid("6e6e3f65-16bc-43ac-b29a-149444ce933b"),
                            Date = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Unit = 1,
                            Weight = 200m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
